### ISSUE TITLE
set up issue tracker on forked repo

### ISSUE THREAD

**Issue by orbeckst** [ASU-CompMethodsPhysics-PHY494/final-rendezvous-with-ramageddon#4]
@andywinhold , I suggest you enable the issue tracker on https://github.com/andywinhold/aworbits – by default it is not enabled for forks (the idea being that development continues in the original repo) but in this case you want to continue in your fork.

The issue tracker can be enabled under settings.

Once you have an issue tracker I and @ianmkenney can use it to make further suggestions.

**Comment by andywinhold** [comment]
@orbeckst Thank you for telling me about this. I have opened the issue tracker under https://github.com/andywinhold/aworbits. Any input is greatly appreciated!
